### ISSUE TITLE
Keys for apt-get need to be updated

### ISSUE THREAD

**Issue by salvor-hardin** [kpcyrd/acme-redirect#36]
Err:5 https://apt.vulns.sexy stable InRelease
  The following signatures were invalid: EXPKEYSIG 45A650E2638C536D kpcyrd <git@rxv.cc>
Fetched 14.0 kB in 1s (10.3 kB/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.vulns.sexy stable InRelease: The following signatures were invalid: EXPKEYSIG 45A650E2638C536D kpcyrd <git@rxv.cc>
W: Failed to fetch https://apt.vulns.sexy/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 45A650E2638C536D kpcyrd <git@rxv.cc>
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by kpcyrd** [comment]
The updated key is [available here](https://apt.vulns.sexy/kpcyrd.pgp), depending on how you originally imported the key you need to update it differently, the strategy apt currently recommends is putting the file at `/etc/apt/trusted.gpg.d/kpcyrd.gpg`.

Unfortunately apt is somewhat buggy in that regard, if the expired key is in `/etc/apt/trusted.gpg` (which was deprecated by the latest debian release) you need to remove the expired key from there too or the key from `/etc/apt/trusted.gpg.d/kpcyrd.gpg` won't be picked up. On my systems it was fine just running `rm /etc/apt/trusted.gpg /etc/apt/trusted.gpg~` but check with `apt-key list` first if there are still any keys in there that you need.

**Comment by salvor-hardin** [comment]
Thank you for the tips.
Removed the entry with apt-key del 
Then added your file with apt-key add kpcyrd.pgp 
That made it work

Thanks.
