### ISSUE TITLE
Can't issue certificates for multiple domain names anymore

### ISSUE THREAD

**Issue by kpcyrd** [kpcyrd/acme-redirect#40]
Today I noticed a certificate stopped renewing:

```
[2024-10-02T08:52:26Z INFO  ureq::unit] sending request POST https://acme-v02.api.letsencrypt.org/acme/finalize/<redacted>/<redacted>
[2024-10-02T08:52:26Z ERROR acme_redirect::renew] Failed to renew ("sn0int.com"): Fail to get certificate "sn0int.com": urn:ietf:params:acme:error:rejectedIdentifier: Error finalizing order :: Cannot issue for "sn0int.com, dns:www.sn0int.com": Domain name contains an invalid character
```

I'm very interested in a fix for this, I'm trying to read up on acme internals when time permits.

**Comment by andre-santos1** [comment]
I got same error a few hours ago. Any fixes for that?

**Comment by kpcyrd** [comment]
Not yet, there's some discussion about an apparent change in validation rules, that links to a pull request and git commits, but I couldn't figure a specific change that seems related:

https://community.letsencrypt.org/t/domain-name-contains-an-invalid-character/220411

**Comment by kpcyrd** [comment]
I've merged a fix in #44, feel free to try again with the current git main branch, if nobody reports any issues I'm going to cut a new release soon.

**Comment by kpcyrd** [comment]
This has been fixed in the latest 0.7.0 release.

**Comment by kpcyrd** [comment]
There's now also a technical writeup explaining the details: https://log.woodweb.ca/articles/openssl-rs-sans/

**Comment by alerque** [comment]
I nice write up, and hats off to everybody involved in chancing it down and fixing the bug at least for this app with a howto for others.
