### ISSUE TITLE
Cannot Build from source with Debian 12 Bookworm packages with rust 1.63.0

### ISSUE THREAD

**Issue by salvor-hardin** [kpcyrd/acme-redirect#45]
Cannot Build from source with Debian 12 Bookworm packages with rust 1.63.0
Debian 12 is the current version... 

`
Resolving deltas: 100% (457/457), done.
    Updating crates.io index
error: failed to select a version for `env_logger`.
    ... required by package `acme-redirect v0.7.0 (/tmp/cargo/acme-redirect)`
versions that meet the requirements `^0.11` (locked to 0.11.5) are: 0.11.5

the package `acme-redirect` depends on `env_logger`, with features: `anstream` but `env_logger` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.
`

**Comment by salvor-hardin** [comment]
This script would work, perhaps you can take some hints and update documentation.

Mainly removes any rustc or cargo binaries, installs the latest, git downloads acme-redirect, installs and then removes cargo and rustc as/if they are not needed. All is unattended.

```
rm -Rf /tmp/acme
mkdir -p /tmp/acme
cd /tmp/acme

apt-get -y remove cargo rustc
apt -y autoremove

# install latest rust and cargo
curl https://sh.rustup.rs -sSf | sh -s -- -y

# enable paths without ssh restart 
. "$HOME/.cargo/env" 


git clone https://github.com/kpcyrd/acme-redirect.git
cd acme-redirect/
cargo build --release

install -Dm 755 -t /usr/bin \
    target/release/acme-redirect

install -Dm 644 contrib/confs/acme-redirect.conf -t /etc
install -Dm 644 contrib/confs/certs.d/example.com.conf /etc/acme-redirect.d/example.com.conf.sample

cd /tmp
rm -Rf /tmp/acme

# uninstall rust and cargo
rustup self uninstall -y

acme-redirect -V

```

**Comment by kpcyrd** [comment]
Thanks for sharing :) The officially recommended way on Debian is either building with the rustup compiler, or installing through the Debian package from https://apt.vulns.xyz/

Instructions to use reproducible builds to re-create a bit-for-bit identical .deb file from source can be found in the git repository: https://github.com/kpcyrd/apt-vulns-xyz
